src/Entity/Eleve.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EleveRepository")
 */
class Eleve
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Evaluation", inversedBy="eleves")
     */
    private $evaluation;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Matiere", inversedBy="eleves")
     */
    private $matieres;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Representant", inversedBy="eleves")
     */
    private $representants;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AbsenceRetard", mappedBy="noms_eleves")
     */
    private $absences;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Utilisateur", cascade={"persist", "remove"})
     */
    private $role_id;

    public function __construct()
    {
        $this->evaluation = new ArrayCollection();
        $this->matieres = new ArrayCollection();
        $this->absences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    /**
     * @return Collection|Evaluation[]
     */
    public function getEvaluation(): Collection
    {
        return $this->evaluation;
    }

    public function addEvaluation(Evaluation $evaluation): self
    {
        if (!$this->evaluation->contains($evaluation)) {
            $this->evaluation[] = $evaluation;
        }

        return $this;
    }

    public function removeEvaluation(Evaluation $evaluation): self
    {
        if ($this->evaluation->contains($evaluation)) {
            $this->evaluation->removeElement($evaluation);
        }

        return $this;
    }

    /**
     * @return Collection|Matiere[]
     */
    public function getMatieres(): Collection
    {
        return $this->matieres;
    }

    public function addMatiere(Matiere $matiere): self
    {
        if (!$this->matieres->contains($matiere)) {
            $this->matieres[] = $matiere;
        }

        return $this;
    }

    public function removeMatiere(Matiere $matiere): self
    {
        if ($this->matieres->contains($matiere)) {
            $this->matieres->removeElement($matiere);
        }

        return $this;
    }

    public function getRepresentants(): ?Representant
    {
        return $this->representants;
    }

    public function setRepresentants(?Representant $representants): self
    {
        $this->representants = $representants;

        return $this;
    }

    /**
     * @return Collection|AbsenceRetard[]
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(AbsenceRetard $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setNomsEleves($this);
        }

        return $this;
    }

    public function removeAbsence(AbsenceRetard $absence): self
    {
        if ($this->absences->contains($absence)) {
            $this->absences->removeElement($absence);
            // set the owning side to null (unless already changed)
            if ($absence->getNomsEleves() === $this) {
                $absence->setNomsEleves(null);
            }
        }

        return $this;
    }

    public function getRoleId(): ?Utilisateur
    {
        return $this->role_id;
    }

    public function setRoleId(?Utilisateur $role_id): self
    {
        $this->role_id = $role_id;

        return $this;
    }

    public function __toString() 
    {
        return $this->nom;
    }
    public function eraseCredentials() {}

    public function getSalt() {}


}

src/Form/EleveType.php
<?php

namespace App\Form;

use App\Entity\Eleve;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EleveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('telephone')
            ->add('genre')
            ->add('date_naissance')
            ->add('evaluation')
            ->add('matieres')
            ->add('representants')
            ->add('role_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Eleve::class,
        ]);
    }
}

src/Controller/EleveController.php
<?php

namespace App\Controller;

use App\Entity\Eleve;
use App\Form\EleveType;
use App\Repository\EleveRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/eleve")
 */
class EleveController extends AbstractController
{
    /**
     * @Route("/", name="eleve_index", methods="GET")
     */
    public function index(EleveRepository $eleveRepository): Response
    {
        return $this->render('eleve/index.html.twig', ['eleves' => $eleveRepository->findAll()]);
    }

    /**
     * @Route("/new", name="eleve_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $eleve = new Eleve();
        $form = $this->createForm(EleveType::class, $eleve);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($eleve);
            $em->flush();

            return $this->redirectToRoute('eleve_index');
        }

        return $this->render('eleve/new.html.twig', [
            'eleve' => $eleve,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="eleve_show", methods="GET")
     */
    public function show(Eleve $eleve): Response
    {
        return $this->render('eleve/show.html.twig', ['eleve' => $eleve]);
    }

    /**
     * @Route("/{id}/edit", name="eleve_edit", methods="GET|POST")
     */
    public function edit(Request $request, Eleve $eleve): Response
    {
        $form = $this->createForm(EleveType::class, $eleve);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('eleve_index', ['id' => $eleve->getId()]);
        }

        return $this->render('eleve/edit.html.twig', [
            'eleve' => $eleve,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="eleve_delete", methods="DELETE")
     */
    public function delete(Request $request, Eleve $eleve): Response
    {
        if ($this->isCsrfTokenValid('delete'.$eleve->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($eleve);
            $em->flush();
        }

        return $this->redirectToRoute('eleve_index');
    }
}

templates/eleve/_delete_form.html.twig
<form method="post" action="{{ path('eleve_delete', {'id': eleve.id}) }}" onsubmit="return confirm('etes-vous sûr.e de vouloir supprimer toutes les données associées à cet élève?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ eleve.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/eleve/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/eleve/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Eleve{% endblock %}

{% block body %}
    <h1>Modifier les informations d'un éleve</h1>

    {{ include('eleve/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('eleve_index') }}">retour à la lsite</a>

    {{ include('eleve/_delete_form.html.twig') }}
{% endblock %}

templates/eleve/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Eleve index{% endblock %}

{% block body %}
    <h1>Liste des élèves</h1>

    <table class="table">
        <thead>
            <tr>
                
                <th>Nom</th>
                <th>Prenom</th>
                <th>Email</th>
                <th>Telephone</th>
                <th>Genre</th>
                <th>Date_naissance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for eleve in eleves %}
            <tr>
                
                <td>{{ eleve.nom }}</td>
                <td>{{ eleve.prenom }}</td>
                <td>{{ eleve.email }}</td>
                <td>{{ eleve.telephone }}</td>
                <td>{{ eleve.genre }}</td>
                <td>{{ eleve.dateNaissance ? eleve.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('eleve_show', {'id': eleve.id}) }}">Voir</a>
                    <a href="{{ path('eleve_edit', {'id': eleve.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucun élève !</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('eleve_new') }}">Créer un nouvel élève</a>
{% endblock %}

templates/eleve/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Eleve{% endblock %}

{% block body %}
    <h1>Ajouter un nouvel élève</h1>

    {{ include('eleve/_form.html.twig') }}

    <a href="{{ path('eleve_index') }}">Retour à la liste</a>
{% endblock %}

templates/eleve/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Eleve{% endblock %}

{% block body %}
    <h1>Eleve</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ eleve.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ eleve.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ eleve.email }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ eleve.telephone }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{{ eleve.genre }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ eleve.dateNaissance ? eleve.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('eleve_index') }}">Retour à la liste</a>

    <a href="{{ path('eleve_edit', {'id': eleve.id}) }}">Modifier</a>

    {{ include('eleve/_delete_form.html.twig') }}
{% endblock %}