src/Entity/AbsenceRetard.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AbsenceRetardRepository")
 */
class AbsenceRetard
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $motif;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Eleve", inversedBy="absences")
     */
    private $noms_eleves;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }

    public function getNomsEleves(): ?Eleve
    {
        return $this->noms_eleves;
    }

    public function setNomsEleves(?Eleve $noms_eleves): self
    {
        $this->noms_eleves = $noms_eleves;

        return $this;
    }

        public function __toString() 
    {
        return $this->motif;
    }
}

src/Form/AbsenceRetardType.php
<?php

namespace App\Form;

use App\Entity\AbsenceRetard;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AbsenceRetardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_debut')
            ->add('date_fin')
            ->add('motif')
            ->add('noms_eleves')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AbsenceRetard::class,
        ]);
    }
}

src/Controller/AbsenceRetardController.php
<?php

namespace App\Controller;

use App\Entity\AbsenceRetard;
use App\Form\AbsenceRetardType;
use App\Repository\AbsenceRetardRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/absence/retard")
 */
class AbsenceRetardController extends AbstractController
{
    /**
     * @Route("/", name="absence_retard_index", methods="GET")
     */
    public function index(AbsenceRetardRepository $absenceRetardRepository): Response
    {
        return $this->render('absence_retard/index.html.twig', ['absence_retards' => $absenceRetardRepository->findAll()]);
    }

    /**
     * @Route("/new", name="absence_retard_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $absenceRetard = new AbsenceRetard();
        $form = $this->createForm(AbsenceRetardType::class, $absenceRetard);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($absenceRetard);
            $em->flush();

            return $this->redirectToRoute('absence_retard_index');
        }

        return $this->render('absence_retard/new.html.twig', [
            'absence_retard' => $absenceRetard,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="absence_retard_show", methods="GET")
     */
    public function show(AbsenceRetard $absenceRetard): Response
    {
        return $this->render('absence_retard/show.html.twig', ['absence_retard' => $absenceRetard]);
    }

    /**
     * @Route("/{id}/edit", name="absence_retard_edit", methods="GET|POST")
     */
    public function edit(Request $request, AbsenceRetard $absenceRetard): Response
    {
        $form = $this->createForm(AbsenceRetardType::class, $absenceRetard);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('absence_retard_index', ['id' => $absenceRetard->getId()]);
        }

        return $this->render('absence_retard/edit.html.twig', [
            'absence_retard' => $absenceRetard,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="absence_retard_delete", methods="DELETE")
     */
    public function delete(Request $request, AbsenceRetard $absenceRetard): Response
    {
        if ($this->isCsrfTokenValid('delete'.$absenceRetard->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($absenceRetard);
            $em->flush();
        }

        return $this->redirectToRoute('absence_retard_index');
    }
}

templates/absence_retard/_delete_form.html.twig
<form method="post" action="{{ path('absence_retard_delete', {'id': absence_retard.id}) }}" onsubmit="return confirm('Etes vous sûr.e de vouloir supprimer les données concernant ce retard ou cette absence??');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ absence_retard.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/absence_retard/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/absence_retard/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AbsenceRetard{% endblock %}

{% block body %}
    <h1>Modifier une absence ou un retard</h1>

    {{ include('absence_retard/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('absence_retard_index') }}">Retour à la liste</a>

    {{ include('absence_retard/_delete_form.html.twig') }}
{% endblock %}

templates/absence_retard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AbsenceRetard index{% endblock %}

{% block body %}
    <h1>Liste des absence et/ou retards</h1>

    <table class="table">
        <thead>
            <tr>
              
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Motif</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for absence_retard in absence_retards %}
            <tr>
                
                <td>{{ absence_retard.dateDebut ? absence_retard.dateDebut|date('d-m-Y') : '' }}</td>
                <td>{{ absence_retard.dateFin ? absence_retard.dateFin|date('d-m-Y') : '' }}</td>
                <td>{{ absence_retard.motif }}</td>
                <td>
                    <a href="{{ path('absence_retard_show', {'id': absence_retard.id}) }}">Détails</a>
                    <a href="{{ path('absence_retard_edit', {'id': absence_retard.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucun retard et aucune absence!</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('absence_retard_new') }}">Ajouter un nouveau retard/une nouvelle absence</a>
{% endblock %}

templates/absence_retard/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AbsenceRetard{% endblock %}

{% block body %}
    <h1>Ajouter un retard/une absence</h1>

    {{ include('absence_retard/_form.html.twig') }}

    <a href="{{ path('absence_retard_index') }}">retour à la liste</a>
{% endblock %}

templates/absence_retard/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AbsenceRetard{% endblock %}

{% block body %}
    <h1>Détails de l'absence</h1>

    <table class="table">
        <tbody>

            <tr>
                <th>Date_debut</th>
                <td>{{ absence_retard.dateDebut ? absence_retard.dateDebut|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ absence_retard.dateFin ? absence_retard.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Motif</th>
                <td>{{ absence_retard.motif }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('absence_retard_index') }}">Retour à la liste</a>

    <a href="{{ path('absence_retard_edit', {'id': absence_retard.id}) }}">Modifier</a>

    {{ include('absence_retard/_delete_form.html.twig') }}
{% endblock %}