src/Entity/Representant.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RepresentantRepository")
 */
class Representant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_2;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Eleve", mappedBy="representants")
     */
    private $eleves;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Utilisateur", cascade={"persist", "remove"})
     */
    private $role_id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Utilisateur", cascade={"persist", "remove"})
     */
    private $roles;

    public function __construct()
    {
        $this->eleves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse1(): ?string
    {
        return $this->adresse_1;
    }

    public function setAdresse1(string $adresse_1): self
    {
        $this->adresse_1 = $adresse_1;

        return $this;
    }

    public function getAdresse2(): ?string
    {
        return $this->adresse_2;
    }

    public function setAdresse2(string $adresse_2): self
    {
        $this->adresse_2 = $adresse_2;

        return $this;
    }

    public function getTelephone1(): ?string
    {
        return $this->telephone_1;
    }

    public function setTelephone1(?string $telephone_1): self
    {
        $this->telephone_1 = $telephone_1;

        return $this;
    }

    public function getTelephone2(): ?string
    {
        return $this->telephone_2;
    }

    public function setTelephone2(?string $telephone_2): self
    {
        $this->telephone_2 = $telephone_2;

        return $this;
    }

    public function getEmail1(): ?string
    {
        return $this->email_1;
    }

    public function setEmail1(?string $email_1): self
    {
        $this->email_1 = $email_1;

        return $this;
    }

    public function getEmail2(): ?string
    {
        return $this->email_2;
    }

    public function setEmail2(?string $email_2): self
    {
        $this->email_2 = $email_2;

        return $this;
    }

    /**
     * @return Collection|Eleve[]
     */
    public function getEleves(): Collection
    {
        return $this->eleves;
    }

    public function addElefe(Eleve $elefe): self
    {
        if (!$this->eleves->contains($elefe)) {
            $this->eleves[] = $elefe;
            $elefe->setRepresentants($this);
        }

        return $this;
    }

    public function removeElefe(Eleve $elefe): self
    {
        if ($this->eleves->contains($elefe)) {
            $this->eleves->removeElement($elefe);
            // set the owning side to null (unless already changed)
            if ($elefe->getRepresentants() === $this) {
                $elefe->setRepresentants(null);
            }
        }

        return $this;
    }

    public function getRoleId(): ?Utilisateur
    {
        return $this->role_id;
    }

    public function setRoleId(?Utilisateur $role_id): self
    {
        $this->role_id = $role_id;

        return $this;
    }

    public function getRoles(): ?Utilisateur
    {
        return $this->roles;
    }

    public function setRoles(?Utilisateur $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

        public function __toString() 
    {
        return $this->nom;
    }
}

src/Form/RepresentantType.php
<?php

namespace App\Form;

use App\Entity\Representant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RepresentantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('adresse_1')
            ->add('adresse_2')
            ->add('telephone_1')
            ->add('telephone_2')
            ->add('email_1')
            ->add('email_2')
            ->add('role_id')
            ->add('roles')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Representant::class,
        ]);
    }
}

src/Controller/RepresentantController.php
<?php

namespace App\Controller;

use App\Entity\Representant;
use App\Form\RepresentantType;
use App\Repository\RepresentantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/representant")
 */
class RepresentantController extends AbstractController
{
    /**
     * @Route("/", name="representant_index", methods="GET")
     */
    public function index(RepresentantRepository $representantRepository): Response
    {
        return $this->render('representant/index.html.twig', ['representants' => $representantRepository->findAll()]);
    }

    /**
     * @Route("/new", name="representant_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $representant = new Representant();
        $form = $this->createForm(RepresentantType::class, $representant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($representant);
            $em->flush();

            return $this->redirectToRoute('representant_index');
        }

        return $this->render('representant/new.html.twig', [
            'representant' => $representant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="representant_show", methods="GET")
     */
    public function show(Representant $representant): Response
    {
        return $this->render('representant/show.html.twig', ['representant' => $representant]);
    }

    /**
     * @Route("/{id}/edit", name="representant_edit", methods="GET|POST")
     */
    public function edit(Request $request, Representant $representant): Response
    {
        $form = $this->createForm(RepresentantType::class, $representant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('representant_index', ['id' => $representant->getId()]);
        }

        return $this->render('representant/edit.html.twig', [
            'representant' => $representant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="representant_delete", methods="DELETE")
     */
    public function delete(Request $request, Representant $representant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$representant->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($representant);
            $em->flush();
        }

        return $this->redirectToRoute('representant_index');
    }
}

templates/representant/_delete_form.html.twig
<form method="post" action="{{ path('representant_delete', {'id': representant.id}) }}" onsubmit="return confirm('Etes-vous certain.e de vouloir supprimer la fiche de ce parent d'élève?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ representant.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/representant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/representant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Representant{% endblock %}

{% block body %}
    <h1>modifier la fiche du parent d'élève</h1>

    {{ include('representant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('representant_index') }}">Retour à la liste</a>

    {{ include('representant/_delete_form.html.twig') }}
{% endblock %}

templates/representant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Representant index{% endblock %}

{% block body %}
    <h1>Parents d'élèves</h1>

    <table class="table">
        <thead>
            <tr>
             
                <th>Nom</th>
                <th>Prenom</th>
                <th>Adresse_1</th>
                <th>Adresse_2</th>
                <th>Telephone_1</th>
                <th>Telephone_2</th>
                <th>Email_1</th>
                <th>Email_2</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for representant in representants %}
            <tr>
         
                <td>{{ representant.nom }}</td>
                <td>{{ representant.prenom }}</td>
                <td>{{ representant.adresse1 }}</td>
                <td>{{ representant.adresse2 }}</td>
                <td>{{ representant.telephone1 }}</td>
                <td>{{ representant.telephone2 }}</td>
                <td>{{ representant.email1 }}</td>
                <td>{{ representant.email2 }}</td>
                <td>
                    <a href="{{ path('representant_show', {'id': representant.id}) }}">Voir</a>
                    <a href="{{ path('representant_edit', {'id': representant.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Rien à afficher</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('representant_new') }}">Ajouter un nouveau parent</a>
{% endblock %}

templates/representant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Parent{% endblock %}

{% block body %}
    <h1>Ajouter un nouveau parent d'élèvet</h1>

    {{ include('representant/_form.html.twig') }}

    <a href="{{ path('representant_index') }}">Retour à la liste</a>
{% endblock %}

templates/representant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parent{% endblock %}

{% block body %}
    <h1>Parent d'élève</h1>

    <table class="table">
        <tbody>

            <tr>
                <th>Nom</th>
                <td>{{ representant.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ representant.prenom }}</td>
            </tr>
            <tr>
                <th>Adresse_1</th>
                <td>{{ representant.adresse1 }}</td>
            </tr>
            <tr>
                <th>Adresse_2</th>
                <td>{{ representant.adresse2 }}</td>
            </tr>
            <tr>
                <th>Telephone_1</th>
                <td>{{ representant.telephone1 }}</td>
            </tr>
            <tr>
                <th>Telephone_2</th>
                <td>{{ representant.telephone2 }}</td>
            </tr>
            <tr>
                <th>Email_1</th>
                <td>{{ representant.email1 }}</td>
            </tr>
            <tr>
                <th>Email_2</th>
                <td>{{ representant.email2 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('representant_index') }}">retour à la liste</a>

    <a href="{{ path('representant_edit', {'id': representant.id}) }}">Modifier</a>

    {{ include('representant/_delete_form.html.twig') }}
{% endblock %}